# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=5)),
                ('owner', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gasInspection', models.BooleanField(default=False)),
                ('electricityInspection', models.BooleanField(default=False)),
                ('chimneyInspection', models.BooleanField(default=False)),
                ('buildingInspection', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=60)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Building')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=512)),
                ('username', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=15)),
                ('canCheck', models.BooleanField(default=False)),
                ('gasPermission', models.BooleanField(default=False)),
                ('electricityPermission', models.BooleanField(default=False)),
                ('chimneyPermission', models.BooleanField(default=False)),
                ('buildingPermission', models.BooleanField(default=False)),
                ('isRegionalInspector', models.BooleanField(default=False)),
                ('isStateInspector', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.User_Type'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='controller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User'),
        ),
    ]
